### ISSUE TITLE
Unable to parse single-column csv files

### ISSUE THREAD

**Issue by cwang** [Unstructured-IO/unstructured#2616]
**Describe the bug**
Given a single column csv file (see one example as attached), it fails to parse it because of the failure of determining the delimiter. 
See https://github.com/Unstructured-IO/unstructured/blob/4096a38371bae062832b976dc7ebff4184b7991f/unstructured/partition/csv.py#L109 for where the issue is. 

**To Reproduce**
Use the file attach to be parsed. 

**Expected behavior**
It should be parsed successfully and treated as a single-column spreadsheet.

**Screenshots**

**Environment Info**
unstructured.io 0.11.8 
Python 3.10

**Additional context**
Here's a 16yo Python bug that's relevant to the `sniff` function used here for the expected behaviour, https://bugs.python.org/issue2078:
[test_single_column.csv](https://github.com/Unstructured-IO/unstructured/files/14512026/test_single_column.csv)

**Comment by MthwRobinson** [comment]
Thanks @cwang - will take a look as soon as we are able

**Comment by cbrendanprice** [comment]
just ran into this today. seems like a pretty simple fix; just need to catch the error on [invocation of `get_delimiter`](https://github.com/Unstructured-IO/unstructured/blob/0.15.0/unstructured/partition/csv.py#L90) and conditionally skip passing the `sep` argument on failure. happy to create a pr for this if that's preferable.

**Comment by scanny** [comment]
@cbrendanprice can you post the full stack trace?

**Comment by cbrendanprice** [comment]
sure. im also creating a pr for this presently. let me know if i should stop.

```
Traceback (most recent call last):
  File "/home/notebook-user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/prepline_general/api/general.py", line 786, in general_partition
    list(response_generator(is_multipart=False))[0]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/prepline_general/api/general.py", line 721, in response_generator
    response = pipeline_api(
               ^^^^^^^^^^^^^
  File "/home/notebook-user/prepline_general/api/general.py", line 420, in pipeline_api
    elements = partition(**partition_kwargs)  # type: ignore # pyright: ignore[reportGeneralTypeIssues]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/auto.py", line 307, in partition
    elements = _partition_csv(
               ^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/documents/elements.py", line 593, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 429, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/file_utils/filetype.py", line 385, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/chunking/dispatch.py", line 74, in wrapper
    elements = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/csv.py", line 90, in partition_csv
    delimiter = get_delimiter(file=f)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/notebook-user/.local/lib/python3.11/site-packages/unstructured/partition/csv.py", line 134, in get_delimiter
    return sniffer.sniff(data, delimiters=",;").delimiter
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/csv.py", line 187, in sniff
    raise Error("Could not determine delimiter")
_csv.Error: Could not determine delimiter
```

**Comment by scanny** [comment]
@cbrendanprice Ah, okay, I see what you mean now.

A quick PR would be helpful. I'm interested whether Pandas can parse single-column CSV, so if you could prove out your idea that would be a help. You'd need to add a test case that currently fails, I expect that means adding a `single-column.csv` file to `/example-docs`.

I think what you're proposing is that on `_csv.Error` we assume `sep=","`. I believe Pandas will produce the same error if `sep=None`.

**Comment by cbrendanprice** [comment]
done! and accounted for all of what you mentioned here in my own tests. you are correct in that pandas fails on passing a sep of None, so i decided to simply omit the separator altgother, which in my testing results in a pandas correctly/successfully reading the csv. just posted [my pr for this](https://github.com/Unstructured-IO/unstructured/pull/3439).

**Comment by danieloop** [comment]
I'm still facing problems with single-column csv files. I saw current implementation, after the fix made [here](https://github.com/Unstructured-IO/unstructured/pull/3483) and I think it depends on the data present on the single-column csv.

In the file added for tests in the repo, the _CsvPartitioningContext object determines sep is None, and that makes the pd.read_csv to fail. 
But with a single-column csv even simpler than the test one, for example, having : "Header\nValue1\nValue2\nValue3\nValue4", the _CsvPartitioningContext object determines sep is None too, but then passing that sep=None to pd.read_csv, that falls back to python engine and determines the separator is "e", so, finally, in this case I end up with a successful partition, with a single element with following text: "H ad r Valu 1 None Valu 2 None Valu 3 None Valu 4 None", that is incorrect.
