### ISSUE TITLE
bug/_download_nltk_packages_if_not_present throws HTTP 403 Forbidden

### ISSUE THREAD

**Issue by tn-halfspace** [Unstructured-IO/unstructured#3795]
**Describe the bug**
Until 25.11.2024 I haven't seen any problems with this function. Since now this url:

https://utic-public-cf.s3.amazonaws.com/nltk_data_3.8.2.tar.gz

Returned 403.

Edit: it's back up there... But seems inconsistent.

**Comment by villagab4** [comment]
Also experiencing this issue !

**Comment by derekhsu** [comment]
I still have the issue now. Where can I download and install it?

**Comment by akhilkapil** [comment]
Hi @tn-halfspace, were you able to resolve this issue?

**Comment by tn-halfspace** [comment]
This is ridiculous @Unstructured-DevOps. It hapenned again today.

I've created my own workaround to use nltk's downloader directly instead of relying on unstructured.nlp downloader and download the two packages that are used by unstructured.io (`averaged_perceptron_tagger_eng` and `punkt_tab`)

I think in a perfect world the best practice would be to ship your code with these two packages and use manual installation by changing the NLTK_PATH according to [NLTK documentation](https://www.nltk.org/data.html#manual-installation)

**Comment by vangheem** [comment]
If you upgrade to the latest, it should be fixed: https://github.com/Unstructured-IO/unstructured/pull/3796

**Comment by skshetry** [comment]
I am still getting AccessDenied. @vangheem, would it be possible to keep the URL up?

We are still stuck with an older version of unstructured due to #3731 at the moment.

**Comment by kartik4949** [comment]
Following could be a hack for solving this issue.
```python
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

```

**Comment by djibomar** [comment]
This started happening for us today as well.  The previous version used to call this s3 url to download nltk https://utic-public-cf.s3.amazonaws.com/nltk_data_3.8.2.tar.gz however it now just throws a 403.
Why did this happen ?

**Comment by jexp** [comment]
Same here, we're also seeing the 403 errors.

**Comment by dipanjanS** [comment]
This is still happening and has broken all our pipelines

**Comment by jan-schneider3** [comment]
Same here

**Comment by zya** [comment]
Updating to 0.16.11 seems to have addressed the issue for me.

**Comment by dipanjanS** [comment]
Still doesnt work even with 0.16.11, literally the same issue but 0.15 seems to be working, this is really frustrating

![image](https://github.com/user-attachments/assets/e752692f-5bf4-42f0-ba6b-56466a978407)

**Comment by dipanjanS** [comment]
Reinstalled everything and reupdated, its working now with the latest version so far, however I have other issues now where the outputs have changed :) but that's for another day (issue). Thanks for all the suggestions in this thread!

**Comment by doyeka** [comment]
> If you upgrade to the latest, it should be fixed: #3796

Can confirm upgrading to the latest version of unstructured (0.16.11) resolved the bug for me.

**Comment by scanny** [comment]
Closing as resolved. If you're still having trouble feel free to reopen.
